# Generated by Django 3.2.9 on 2021-12-20 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_user', '0002_userrecipe_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='author_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
