# Generated by Django 3.2.9 on 2021-11-26 19:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('ingredients', models.TextField()),
                ('excerpt', models.CharField(max_length=250)),
                ('main_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('slug', models.SlugField(unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('approved', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('public_private', models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
