# Generated by Django 3.2.9 on 2021-12-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0004_auto_20211127_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
