# Generated by Django 3.2.9 on 2021-12-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0005_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='public_private',
        ),
    ]
