# Generated by Django 3.2.9 on 2021-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0006_remove_recipe_public_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public_private',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
    ]
