# Generated by Django 3.2.9 on 2021-12-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0007_recipe_public_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='B', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
