# Generated by Django 3.2.9 on 2021-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0012_auto_20211210_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='list',
            field=models.TextField(default='ingredients list'),
        ),
    ]
