# Generated by Django 3.2.9 on 2021-12-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0013_recipe_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='list',
            field=models.TextField(blank=True),
        ),
    ]
