# Generated by Django 3.2.9 on 2021-12-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0016_userrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
