# Generated by Django 3.2.9 on 2021-12-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0017_delete_userrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
