# Generated by Django 3.2.9 on 2021-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('ingredients_list', models.TextField(blank=True)),
                ('public_private', models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
            ],
        ),
    ]
