# Generated by Django 3.2.9 on 2021-12-13 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
